// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-stories.ts
import { createClient } from "npm:@supabase/supabase-js@^2.106.1";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function supabaseForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var list_stories_default = defineTool({
  name: "list_stories",
  title: "List stories",
  description: "List the signed-in user's stories from their Story Cloud, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Maximum number of stories to return."),
    search: z.string().trim().optional().describe("Optional case-insensitive substring match on the story title.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, search }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    let query = supabaseForUser(ctx).from("stories").select("id,title,category,tags,created_at,updated_at,is_public").eq("user_id", ctx.getUserId()).order("updated_at", { ascending: false }).limit(limit);
    if (search) query = query.ilike("title", `%${search}%`);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { stories: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-story.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.106.1";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
function supabaseForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_story_default = defineTool2({
  name: "get_story",
  title: "Get story",
  description: "Fetch the full content of one of the signed-in user's stories by ID.",
  inputSchema: {
    id: z2.string().uuid().describe("The story's UUID.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser2(ctx).from("stories").select("*").eq("id", id).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Story not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { story: data }
    };
  }
});

// src/lib/mcp/tools/create-story.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.106.1";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
function supabaseForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var create_story_default = defineTool3({
  name: "create_story",
  title: "Create story",
  description: "Save a new story to the signed-in user's Story Cloud.",
  inputSchema: {
    title: z3.string().trim().min(1).max(200).describe("Story title."),
    body: z3.string().trim().min(1).describe("Full story text."),
    tags: z3.array(z3.string().trim().min(1)).max(20).optional().describe("Optional tags."),
    category: z3.string().trim().optional().describe("Optional category label.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ title, body, tags, category }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { data, error } = await supabaseForUser3(ctx).from("stories").insert({ user_id: ctx.getUserId(), title, body, tags: tags ?? null, category: category ?? null }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Created story ${data.id}` }],
      structuredContent: { story: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "lufhfjptukmgsudemujb";
var mcp_default = defineMcp({
  name: "storyou-mcp",
  title: "Storyou",
  version: "0.1.0",
  instructions: "Tools for Storyou: browse and add stories in the signed-in user's Story Cloud. Use `list_stories` to find stories, `get_story` to read one, and `create_story` to save a new one.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_stories_default, get_story_default, create_story_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
